---
# tasks file for subscribe-sat
- name: Add Satellite server IP
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: '{{ sat_ip }}  {{ satellite }}'
#    create: true
- name: Install katello-ca
  ansible.builtin.dnf:
    name: "http://{{ satellite }}/pub/katello-ca-consumer-latest.noarch.rpm"
    disable_gpg_check: true
    state: present
- name: Subscribe RHEL 7 servers
  community.general.redhat_subscription:
    state: present
    activationkey: '{{ satKey7 }}'
    org_id: 'Red_Hat'
  when: ansible_facts['distribution_major_version'] == "7"
- name: Subscribe RHEL 8 servers
  community.general.redhat_subscription:
    state: present
    activationkey: '{{ satKey8 }}'
    org_id: 'Red_Hat'
  when: ansible_facts['distribution_major_version'] == "8"
- name: Subscribe RHEL 9 servers
  community.general.redhat_subscription:
    state: present
    activationkey: '{{ satKey9 }}'
    org_id: 'Red_Hat'
  when: ansible_facts['distribution_major_version'] == "9"
- name: Install Cockpit on RHEL 7
  ansible.builtin.package:
    name: cockpit
    state: present
  when: ansible_facts['distribution_major_version'] == "7"
- name: Start Cockpit
  ansible.builtin.systemd:
    name: cockpit.socket
    enabled: true
- name: Patch to the latest version
  ansible.builtin.package:
    name: "*"
    state: latest
- name: Reboot
  ansible.builtin.reboot:
    reboot_timeout: 120
