---
# tasks file for idm-hostgroup
- name: Create hostsgroup for clients
  ipahostgroup:
    ipaadmin_password: "{{ admin_password }}"
    name: "{{ idm_host_group }}"
    description: "Client servers"
    host:
      - "{{ inventory_hostname }}"
